spring:
  application:
    name: aggregator

kafka:
  producer:
    bootstrap-servers: localhost:9092

  consumer:
    bootstrap-servers: localhost:9092
    group-id: telemetry.aggregator.sensors
    enable-auto-commit: false
    poll-timeout-ms: 100

    topics:
      sensors: telemetry.sensors.v1