spring:
  application:
    name: aggregator

  config:
    import: "configserver:"

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        use-random-policy: true
        initial-interval: 2000
        max-interval: 10000
        max-attempts: 10

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
